### ISSUE TITLE
can we have $count feature ?

### ISSUE THREAD

**Issue by singhsky** [adamspe/odata-resource#2]

**Comment by adamspe** [comment]
Pushed/published version 0.2.0 which contains support for "count".

I chose to name the relationship `count` as opposed to `$count` since that's more consistent with how other relationships have been named and the library isn't truly implementing odata but re-using many of its parameter names and `$filter` syntax.

See the section in the documentation ([npm](https://www.npmjs.com/package/odata-resource) or [github](https://adamspe.github.io/odata-resource/)) titled "Count (experimental)"

Let me know how this works for you.
